seed: 67
device: "cpu"

# Dataset
kaggle_root: "data"
batch_size: 128
num_workers: 2
use_subset: true
subset_mode: "csv"
subset_csv_path: "provided/training_20_percent.csv"
subset_seed: 67

# Model
model_type: "cgan"
latent_dim: 100
base_channels: 64
num_classes: 10
embed_dim: 64
use_spectral_norm: true

# Training
epochs: 20
lr: 0.0002
run_prefix: "run_cgan"

# Optimizer (Adam)
optimizer:
  name: "adam"
  betas: [0.0, 0.999]
  weight_decay: 0.0

# GAN specific training params
d_updates_per_g: 1

# Evaluation
eval_num_samples: 5000
eval_metrics_batch_size: 32
eval_interval_epochs: 5

wandb:
  enabled: true
  entity: "nunombatista-university-of-coimbra"
  project: "ArtBench-AEGANDIFF"
  tags: ["cgan", "artbench"]
